@extends('layouts.header')

@section('title', 'Reports | SALTiii')

@section('css')
<link href="{{ asset('inside_css/assets/css/saltiii-operations.css') }}" rel="stylesheet" />
@endsection

@section('content')
@php
    $reportOpen = $tasksProgress->where('completed', 0);
    $reportCompletion = $tasksProgress->count() ? (int) round(($tasksCompleted->count() / $tasksProgress->count()) * 100) : 0;
    $projectGroups = $tasksProgress->groupBy('project_id');
@endphp
<div class="operations-page reports-page">
    <header class="operations-header"><div><span class="operations-eyebrow">Operational reporting</span><h1>Workload and delivery reports</h1><p>Use filters to review progress, overdue work, completion, and project concentration.</p></div><button type="button" class="btn operations-primary" onclick="window.print()"><i class="ri-printer-line" aria-hidden="true"></i> Print report</button></header>
    <section class="operations-toolbar"><form method="GET" action="{{ route('task.reports') }}"><label><span>From</span><input type="date" name="date_from" value="{{ request('date_from') }}"></label><label><span>To</span><input type="date" name="date_to" value="{{ request('date_to') }}"></label><label><span>Employee</span><select name="user_id"><option value="">All employees</option>@foreach($users as $employee)<option value="{{ $employee->id }}" {{ request('user_id') == $employee->id ? 'selected' : '' }}>{{ $employee->name }}</option>@endforeach</select></label><label><span>Project</span><select name="project_id"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" {{ request('project_id') == $project->id ? 'selected' : '' }}>{{ $project->name }}</option>@endforeach</select></label><button class="btn btn-primary" type="submit"><i class="ri-filter-3-line" aria-hidden="true"></i> Run report</button><a class="btn btn-light" href="{{ route('task.reports') }}">Clear</a></form></section>
    <section class="operations-signal-strip" aria-label="Report summary"><div><small>Tasks in view</small><strong>{{ $tasksProgress->count() }}</strong><span>Matching the filters</span></div><div><small>Open work</small><strong>{{ $reportOpen->count() }}</strong><span>Not yet completed</span></div><div><small>Overdue</small><strong>{{ $tasksAging->count() }}</strong><span>Past due date</span></div><div><small>Completion</small><strong>{{ $reportCompletion }}%</strong><span>{{ $tasksCompleted->count() }} completed</span></div></section>
    <div class="report-tabs" role="tablist" aria-label="Report views"><button class="is-active" type="button" data-report-tab="projects">Project health</button><button type="button" data-report-tab="aging">Aging</button><button type="button" data-report-tab="completed">Completed</button></div>
    <section class="operations-register" data-report-panel="projects" aria-labelledby="project-report-title"><header class="operations-section-head"><div><span class="operations-eyebrow">Portfolio report</span><h2 id="project-report-title">Project health</h2></div><span>{{ $projectGroups->count() }} projects</span></header><div class="operations-table-wrap"><table class="operations-table"><thead><tr><th>Project</th><th>Total tasks</th><th>Open</th><th>Overdue</th><th>Completed</th><th>Completion</th></tr></thead><tbody>@forelse($projectGroups as $projectId=>$group)<tr><td><strong>{{ optional($group->first()->project)->name ?: 'No project' }}</strong></td><td>{{ $group->count() }}</td><td>{{ $group->where('completed', 0)->count() }}</td><td>{{ $tasksAging->where('project_id', $projectId)->count() }}</td><td>{{ $group->where('completed', 1)->count() }}</td><td><div class="report-progress"><i><b style="width:{{ $group->count() ? round(($group->where('completed', 1)->count() / $group->count()) * 100) : 0 }}%"></b></i><strong>{{ $group->count() ? round(($group->where('completed', 1)->count() / $group->count()) * 100) : 0 }}%</strong></div></td></tr>@empty<tr><td colspan="6"><div class="operations-empty"><i class="ri-bar-chart-box-line" aria-hidden="true"></i><div><strong>No project data</strong><p>Adjust the report filters to include project work.</p></div></div></td></tr>@endforelse</tbody></table></div></section>
    <section class="operations-register" data-report-panel="aging" hidden aria-labelledby="aging-report-title"><header class="operations-section-head"><div><span class="operations-eyebrow">Exception report</span><h2 id="aging-report-title">Overdue tasks</h2></div><span>{{ $tasksAging->count() }} records</span></header><div class="operations-table-wrap"><table class="operations-table"><thead><tr><th>Task</th><th>Project</th><th>Owner</th><th>Due date</th><th>Days overdue</th><th>Priority</th></tr></thead><tbody>@forelse($tasksAging as $task)<tr><td><a href="{{ url('/view-task/'.$task->id) }}"><strong>{{ $task->title }}</strong></a></td><td>{{ optional($task->project)->name ?: 'No project' }}</td><td>{{ $task->users->pluck('name')->implode(', ') ?: 'Unassigned' }}</td><td>{{ $task->due_date ? date('M j, Y', strtotime($task->due_date)) : '—' }}</td><td><strong class="text-danger">{{ $task->due_date ? now()->startOfDay()->diffInDays(\Carbon\Carbon::parse($task->due_date)) : 0 }}</strong></td><td>{{ $task->priority ?: 'Normal' }}</td></tr>@empty<tr><td colspan="6"><div class="operations-empty"><i class="ri-checkbox-circle-line" aria-hidden="true"></i><div><strong>No overdue tasks</strong><p>This report has no aging exceptions.</p></div></div></td></tr>@endforelse</tbody></table></div></section>
    <section class="operations-register" data-report-panel="completed" hidden aria-labelledby="completed-report-title"><header class="operations-section-head"><div><span class="operations-eyebrow">Outcome report</span><h2 id="completed-report-title">Completed work</h2></div><span>{{ $tasksCompleted->count() }} records</span></header><div class="operations-table-wrap"><table class="operations-table"><thead><tr><th>Task</th><th>Project</th><th>Owner</th><th>Completed on</th><th>Priority</th></tr></thead><tbody>@forelse($tasksCompleted as $task)<tr><td><a href="{{ url('/view-task/'.$task->id) }}"><strong>{{ $task->title }}</strong></a></td><td>{{ optional($task->project)->name ?: 'No project' }}</td><td>{{ $task->users->pluck('name')->implode(', ') ?: 'Unassigned' }}</td><td>{{ $task->updated_at->format('M j, Y') }}</td><td>{{ $task->priority ?: 'Normal' }}</td></tr>@empty<tr><td colspan="5"><div class="operations-empty"><i class="ri-checkbox-circle-line" aria-hidden="true"></i><div><strong>No completed tasks</strong><p>No completed work matches these filters.</p></div></div></td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection

@section('js')
<script>document.querySelectorAll('[data-report-tab]').forEach(function(button){button.addEventListener('click',function(){var tab=button.dataset.reportTab;document.querySelectorAll('[data-report-tab]').forEach(function(item){item.classList.toggle('is-active',item===button)});document.querySelectorAll('[data-report-panel]').forEach(function(panel){panel.hidden=panel.dataset.reportPanel!==tab})})});</script>
@endsection
